# ###PRIMERA PETICION
# GET http://localhost:5422/libros

# ###OBTENER LIBRO POR SU ID
# GET http://localhost:5422/libros/1

# ###CREAR UN LIBRO
POST http://localhost:5422/libros
Content-Type: application/json

{
  "titulo": "El coronel no tiene quien le escriba",
  "ano_publicacion": 1990,
  "id_autor": 1
}
###ACTUALIZAR UN LIBRO POR ID

PUT http://localhost:5422/libros/1
Content-Type:application/json

{
  "titulo":"Cien añitos de soledad",
  "ano_publicacion":1987,
  "id_autor":1
}

###Eliminar un libro
DELETE http://localhost:5422/libros/9
Content-Type:application/json
